- .github/workflows/lint-pr.yml
We do not use commit messages when merging the PR to main, relying on the PR title and description instead.
So I don't believe the commit messages benefit from linting, they just add toil
> [BE] Remove gitlint linter

- ali/aws/391835788720/us-east-1/gha_roles.tf
This role allows Packer to run `packer build` to create AMIs.
Issue: pytorch/test-infra#5992
> Add Packer build role

- ali/aws/391835788720/us-east-1/gha_roles.tf
Allow the pytorch/test-infra repo to be able to use the packer role.
Issue: pytorch/test-infra#5992
> Allow test-infra repo to use packer role

- ali/aws/391835788720/us-east-1/variables.tf
update the AMI pinning so it reflects what is already on `pytorch-labs/pytorch-gha-infra` and is on all variants of `scale-config.yml`
> Update AMI pinning  to al2023-ami-2023.6.*

- ali/Terrafile
Main changes since last version is in the PR:
- Fix multi-region support for scaleDown lambda (https://github.com/pytorch/test-infra/pull/6231);
> Release v20250204-163312

- ali/aws/391835788720/us-east-1/variables.tf
AMI Windows 2019 GHA CI - 20250211231335
AMI: ami-0ad04eca090b1e0ff
Based on build: https://github.com/pytorch/test-infra/actions/runs/13274353312/job/37060857180
> Deploy AMI Windows 2019 GHA CI - 20250211231335 to prod

- ali/Terrafile
This release version includes the reuse of ephemeral instances capabilities implemented recently in test-infra.
Its been validated for a week in Meta's infra now. So it is time to update LF infra with those changes that proven to be effective and stable.
> Release v20250310-124810

- ali/Terrafile
- ali/aws/391835788720/us-east-1/autoscaler-lambda-canary.tf
- ali/aws/391835788720/us-east-1/autoscaler-lambda.tf
It mostly includes the new lambda `scaleUpChron`: https://github.com/pytorch/test-infra/pull/6390
> Bump test-infra version to v20250317-134413

- github-admin-permissions.md
Document how the PyTorch Foundation admin permissions to GitHub repos are managed and who the points of contact for them are as well as steps to offboard accounts.
> Document GitHub repo admin access

- ali/aws/391835788720/us-east-1/autoscaler-lambda.tf
It's been about 3 weeks now that we set min runners to 4. Things appear to be pretty stable during that time so lets bump it down further to 2.
Reference 2265996928585909f37ec6f8c1e86bd52e2318b4
> Reduce min runners to 2

- ali/aws/391835788720/us-east-1/variables.tf
The filter for "2023.6.202*" is no longer returning a match. Looks like AWS has moved to 2023.7 for this AMI. Make the search more broad so that hopefully we don't keep running into this issue when AWS removes older images.
> Update Linux AMI filter

- ali/aws/391835788720/us-east-1/variables.tf
After some discussions in ci-infra we decided we should include the major version digit at least until we have a way to track when this version changes on us.
> Add back the major version digit

- arc/aws/391835788720/us-east-1/lf-arc-dev-eks.tf
This change should be a noop when Terraform plan runs. Without this explicitly set everytime a different user runs Terraform it will change the KMS resource principal to the current caller id.
> Explicitly set kms_key_administrators

- ali/aws/391835788720/us-east-1/autoscaler-lambda-canary.tf
- ali/aws/391835788720/us-east-1/autoscaler-lambda.tf
The original value for the minimum running time in production was actually 10 mins ([source PR](https://github.com/pytorch-labs/pytorch-gha-infra/pull/644)), so reverting back to that value to reduce costs.
Pairs with changes from https://github.com/pytorch/test-infra/pull/6684/
> Reduce the amount of time we wait before reclaiming an instance

- ali/Terrafile
Includes a bunch of reliability fixes from:
* https://github.com/pytorch/test-infra/pull/6934
* https://github.com/pytorch/test-infra/pull/6885
* https://github.com/pytorch/test-infra/pull/6933
* https://github.com/pytorch/test-infra/pull/6932
> Update terraform module to same version used by Meta prod

- arc/aws/391835788720/us-east-1/vpc.tf
Allows nodes from EKS cluster to make outbound connections to the internet.
> Setup NAT gateway for ARC private subnet

- ali/aws/391835788720/us-east-1/autoscaler-lambda.tf
Re-attempt now that issues causing the revert
f9df791e35c5dfc23d449ff6279dc04d4d665309 have been addressed.
Considering there is now a scale-up cron job that periodically checks Clickhouse if there are jobs that have been queued for a long time and automatically scales up new runners. We should be able to set min-available to 0 again.
The cron checks this Clickhouse URL
https://hud.pytorch.org/api/clickhouse/queued_jobs_aggregate?parameters=%5B%5D
> Set min-available runners to 0

- arc-backup-2024/scripts/deployment.py
This PR replaces all instances of `pytorch-labs` with `meta-pytorch` in this repository now that the `pytorch-labs` org has been renamed to `meta-pytorch`
- Replaced all occurrences of `pytorch-labs` with `meta-pytorch`
- Only modified files with extensions: .py, .md, .sh, .rst, .cpp, .h, .txt, .yml
- Skipped binary files and files larger than 1MB due to GitHub api payload limits in the script to cover all repos in this org. Will do a more manual second pass later to cover any larger files
This PR updates files that contained the target text.
Generated by automated script on 2025-08-12T20:58:47.637013+00:00Z
> [EZ] Replace `pytorch-labs` with `meta-pytorch`

- arc/aws/391835788720/us-east-1/02_helm/argocd.tf
- arc/aws/391835788720/us-east-1/02_helm/k8s_infra.tf
- arc/aws/391835788720/us-east-1/02_helm/main.tf
- arc/aws/391835788720/us-east-1/02_helm/resources/clusterissuer.yaml.tftpl
- arc/aws/391835788720/us-east-1/02_helm/values/argocd.yaml.tftpl
- arc/aws/391835788720/us-east-1/02_helm/values/cert-manager.yaml
- arc/aws/391835788720/us-east-1/02_helm/values/ingress-nginx.yaml
- arc/aws/391835788720/us-east-1/02_helm/variables.tf
Add cert-manager to the k8s cluster used for ARC.
Add a ClusterIssuer. The email address required for that is pulled from a GitHub secret called CERT_MANAGER_EMAIL that needs to be created. GitHub workflows have been updated accordingly.
Add ingress-nginx to the k8s cluster used for ARC. This ingress works nicely with cert-manager, ArgoCD and the AWS LB infra.
Configure ArgoCD to use an ingress with the domain name argocd.pytorch.org, annotated for cert-manager and nginx. ArgoCD prefers SSL passthrough, because it transports HTTPs and grpc on the same port. Using SSL passthrough also enhances security as the traffic stays encrypted within the cluster as well.
Using SSL passthrough is a bit of an headache for the HTTP01 challenge. Adding a dedicated ingress template to the cluster issuer …
> Add cert-manager and ingress-nginx to ARC

- arc/aws/391835788720/us-east-1/02_helm/arc.tf
- arc/aws/391835788720/us-east-1/02_helm/outputs.tf
- arc/aws/391835788720/us-east-1/02_helm/values/gha-runner-scale-set-controller.yaml
Installs the ARC control plane.
This does not yet create any RunnerScaleSet, it only prepares the terraform code that loads the required secrets from AWS Secret Manager, so that they can be later injected in the relevant namespaces.
> Add ARC control plane via terraform

- .github/workflows/arc-deploy-prod.yml
- arc/aws/391835788720/us-east-1/03_argocd/runner-set-lf-aws.tf
- arc/modules/argocd-runner-scale-set/arc_runner_scale_set.tf
- arc/modules/argocd-runner-scale-set/variables.tf
- argocd/aws/391835788720/us-east-1/in-cluster/lf-aws/linux-20250911-amd64-2c-4g/values.yaml
Several fixes:
* The provider_path for ARC runner scale sets included an unwanted leading space, causing path match to fail.
* Add `TF_VAR_git_revision` to the arc-deploy-prod job so that we can deploy from a PR including changes to the values for the RunnerScaleSet.
* Add a repository definition to the cluster, which is required for OCI based helm charts.
* Add enough permissions to the ArgoCD project to deploy all resources included in the helm chart.
* Add auto-sync to the applicationset template
* Change the local cluster name to `in-cluster` which is ArgoCD default
Signed-off-by: Andrea Frittoli <andrea.frittoli@uk.ibm.com>
> Several fixes to the ApplicationSet for ARC RunnerScaleSets

- argocd/aws/391835788720/us-east-1/in-cluster/lf-aws/linux-20250911-amd64-2c-4g/values.yaml
Configure the test RunnerScaleSet for the pytorch/pytorch git repo only.
> Config the ephemeral runners for pytorch/pytorch

- arc/aws/391835788720/us-east-1/03_argocd/runner-set-lf-aws.tf
- arc/modules/argocd-runner-scale-set/arc_runner_scale_set.tf
- arc/modules/argocd-runner-scale-set/variables.tf
- argocd/aws/391835788720/us-east-1/in-cluster/ubuntu-22-amd64-2c-4g/values.yaml
Change the ApplicationSet module so that each RunnerScaleSet is executed in its own namespace.
Add a role to get read access to secrets and a rolebinding in each namespace.
Also update the RSS name to reflect the OS/version of the runner container image, rather than the containing VM.
> One RSS per namespace. Add role/binding for secrets

- ali/aws/391835788720/us-east-1/variables.tf
V7 is not available anymore, so releases are going to fail.
Meta's infra migrated yesterday successfully, so seems a safe upgrade.
> [ALI] upgrade linux AMI to use AL23 version 8
